import "./globals.css";
import { Manrope } from "next/font/google";
import localFont from "next/font/local";

const polySans = localFont({
  src: [
    { path: "../lib/vendor/PolySans/PolySans-Bulky.woff2", weight: "700", style: "normal" },
    { path: "../lib/vendor/PolySans/PolySans-BulkyItalic.woff2", weight: "700", style: "italic" },
    { path: "../lib/vendor/PolySans/PolySans-Median.woff2", weight: "600", style: "normal" },
    { path: "../lib/vendor/PolySans/PolySans-MedianItalic.woff2", weight: "600", style: "italic" },
    { path: "../lib/vendor/PolySans/PolySans-Neutral.woff2", weight: "500", style: "normal" },
    { path: "../lib/vendor/PolySans/PolySans-NeutralItalic.woff2", weight: "500", style: "italic" },
    { path: "../lib/vendor/PolySans/PolySans-Slim.woff2", weight: "400", style: "normal" },
    { path: "../lib/vendor/PolySans/PolySans-SlimItalic.woff2", weight: "400", style: "italic" },
  ],
  variable: "--font-polysans",
  display: "swap",
});

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
  display: "swap",
});

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${polySans.variable} ${manrope.variable} overflow-x-hidden font-sans`}>{children}</body>
    </html>
  );
}
